name: 'Continuous Integration'

on:
  push:
    branches: 
    - master 

jobs:
  all_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: 'Packages'
      run: |
          sudo apt update && sudo apt install libcunit1-dev gcovr &&
          hg clone https://hg.libsdl.org/SDL SDL
          cd SDL
          mkdir build
          cd build
          ../configure
          make
          sudo make install
    - name: 'Compile'
      run: |
        mkdir Build
        cd Build
        cmake ..
        cmake --build .
    - name: 'Testing'
      run: |
        cd Build
        chmod +x *
        ctest -V
    - name: 'Coverage'
      run: |
        cd Build
        chmod +x *
        make cover_html
    - uses: actions/upload-artifact@v1
      with:
        name: CoverageWeb
        path: Build