name: C - CI


on:
  push:
    branches: master
  pull_request:
    branches: master
    


jobs:
  all_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Packages'
      run: |
         sudo apt update
         sudo apt install libcunit1-dev
         sudo apt install libsdl2-dev
         hg clone https://hg.libsdl.org/SDL SDL
         cd SDL
         mkdir build
         cd build
         ../configure
         make
         sudo make install
         sudo apt install doxygen
    - name: 'Compile'
      run: |
        mkdir BuildCI
        cd BuildCI
        cmake ..
        cmake --build .
    - uses: actions/upload-artifact@v1
      with:
        name: binaries
        path: BuildCI/
